// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BitLocal",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "BitLocal",
            targets: ["AppModule"],
            bundleIdentifier: "app.bitlocal.bitlocal",
            teamIdentifier: "5YUMLYCFT8",
            displayVersion: "1.5",
            bundleVersion: "22",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationWhenInUse(purposeString: "BitLocal asks for your location to find businesses near you. Location sharing is not required to use BitLocal.")
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
